version: '3.8'

services:
  backend:
    build:
      context: ./robotrader_api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./robotrader_api:/app
    env_file:
      - ./robotrader_api/.env
    depends_on:
      - redis
      - postgres
      - influxdb

  frontend:
    build:
      context: ./robotrader-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./robotrader-frontend:/app
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  influxdb:
    image: influxdb:1.8-alpine
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: ${INFLUXDB_DB}
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  redis_data:
  postgres_data:
  influxdb_data:


