"""initial versioned schema

Revision ID: 8d429f0ec081
Revises:
Create Date: 2026-10-04 23:35:08.159822
"""
from __future__ import annotations

import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d429f0ec081'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(name: str) -> bool:
    return sa.inspect(op.get_bind()).has_table(name)


def _index_exists(table_name: str, index_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    if not inspector.has_table(table_name):
        return False
    return any(index.get("name") == index_name for index in inspector.get_indexes(table_name))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists('account_state'):
        op.create_table('account_state',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('balance', sa.Float(), nullable=True),
        sa.Column('initial_capital', sa.Float(), nullable=True),
        sa.Column('last_updated', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('account_id')
        )
    if not _table_exists('admin_users'):
        op.create_table('admin_users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=64), nullable=False),
        sa.Column('password_hash', sa.String(length=256), nullable=False),
        sa.Column('role', sa.String(length=32), nullable=True),
        sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
        sa.Column('mfa_secret', sa.String(length=128), nullable=True),
        sa.Column('is_blocked', sa.Boolean(), nullable=True),
        sa.Column('must_change_pwd', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.Column('failed_attempts', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
        )
    if not _table_exists('ai_observations'):
        op.create_table('ai_observations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('observed_at', sa.DateTime(), nullable=True),
        sa.Column('mode', sa.String(), nullable=False),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('candidate_action', sa.String(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('model_action', sa.String(), nullable=False),
        sa.Column('model_confidence', sa.Float(), nullable=True),
        sa.Column('market_signal_action', sa.String(), nullable=False),
        sa.Column('market_signal_confidence', sa.Float(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('news_sentiment', sa.Float(), nullable=True),
        sa.Column('trend_score', sa.Float(), nullable=True),
        sa.Column('event_blocked', sa.Boolean(), nullable=True),
        sa.Column('risk_valid', sa.Boolean(), nullable=True),
        sa.Column('decision_latency_ms', sa.Float(), nullable=True),
        sa.Column('news_latency_ms', sa.Float(), nullable=True),
        sa.Column('forward_return', sa.Float(), nullable=True),
        sa.Column('outcome_label', sa.Integer(), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists('ai_observations', 'ix_ai_observations_observed_at'):
        op.create_index(op.f('ix_ai_observations_observed_at'), 'ai_observations', ['observed_at'], unique=False)
    if not _index_exists('ai_observations', 'ix_ai_observations_symbol'):
        op.create_index(op.f('ix_ai_observations_symbol'), 'ai_observations', ['symbol'], unique=False)
    if not _index_exists('ai_observations', 'ix_ai_observations_symbol_observed_at'):
        op.create_index('ix_ai_observations_symbol_observed_at', 'ai_observations', ['symbol', 'observed_at'], unique=False)
    if not _table_exists('algorithm_configs'):
        op.create_table('algorithm_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('indicators', sa.JSON(), nullable=True),
        sa.Column('weight', sa.Float(), nullable=True),
        sa.Column('confluence', sa.Float(), nullable=True),
        sa.Column('risk_management', sa.JSON(), nullable=True),
        sa.Column('score', sa.Float(), nullable=True),
        sa.Column('enabled', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
    if not _table_exists('audit_log'):
        op.create_table('audit_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('actor', sa.String(length=128), nullable=False),
        sa.Column('action', sa.String(length=128), nullable=False),
        sa.Column('target_type', sa.String(length=64), nullable=False),
        sa.Column('target_id', sa.String(length=128), nullable=True),
        sa.Column('correlation_id', sa.String(length=128), nullable=True),
        sa.Column('details_json', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists('audit_log', 'ix_audit_log_actor_created_at'):
        op.create_index('ix_audit_log_actor_created_at', 'audit_log', ['actor', 'created_at'], unique=False)
    if not _index_exists('audit_log', 'ix_audit_log_created_at'):
        op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    if not _table_exists('backtest_runs'):
        op.create_table('backtest_runs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('run_id', sa.String(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('timeframe', sa.String(), nullable=False),
        sa.Column('mode', sa.String(), nullable=False),
        sa.Column('dataset_path', sa.String(), nullable=False),
        sa.Column('dataset_sha256', sa.String(), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('initial_capital', sa.Float(), nullable=True),
        sa.Column('final_capital', sa.Float(), nullable=True),
        sa.Column('total_pnl', sa.Float(), nullable=True),
        sa.Column('return_pct', sa.Float(), nullable=True),
        sa.Column('sharpe_ratio', sa.Float(), nullable=True),
        sa.Column('maximum_drawdown', sa.Float(), nullable=True),
        sa.Column('trades_executed', sa.Integer(), nullable=True),
        sa.Column('configuration_json', sa.JSON(), nullable=True),
        sa.Column('result_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists('backtest_runs', 'ix_backtest_runs_created_at'):
        op.create_index(op.f('ix_backtest_runs_created_at'), 'backtest_runs', ['created_at'], unique=False)
    if not _index_exists('backtest_runs', 'ix_backtest_runs_run_id'):
        op.create_index(op.f('ix_backtest_runs_run_id'), 'backtest_runs', ['run_id'], unique=True)
    if not _index_exists('backtest_runs', 'ix_backtest_runs_symbol'):
        op.create_index(op.f('ix_backtest_runs_symbol'), 'backtest_runs', ['symbol'], unique=False)
    if not _table_exists('daily_pnl'):
        op.create_table('daily_pnl',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('pnl', sa.Float(), nullable=True),
        sa.Column('drawdown', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists('data_gaps'):
        op.create_table('data_gaps',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source', sa.String(length=64), nullable=False),
        sa.Column('symbol', sa.String(length=64), nullable=False),
        sa.Column('timeframe', sa.String(length=16), nullable=False),
        sa.Column('gap_start', sa.DateTime(), nullable=False),
        sa.Column('gap_end', sa.DateTime(), nullable=True),
        sa.Column('detected_at', sa.DateTime(), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('details_json', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists('data_gaps', 'ix_data_gaps_symbol_timeframe_detected_at'):
        op.create_index('ix_data_gaps_symbol_timeframe_detected_at', 'data_gaps', ['symbol', 'timeframe', 'detected_at'], unique=False)
    if not _table_exists('decision_snapshots'):
        op.create_table('decision_snapshots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('snapshot_id', sa.String(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('timeframe', sa.String(), nullable=False),
        sa.Column('mode', sa.String(), nullable=False),
        sa.Column('observed_at', sa.DateTime(), nullable=False),
        sa.Column('dataset_path', sa.String(), nullable=True),
        sa.Column('dataset_sha256', sa.String(), nullable=True),
        sa.Column('feature_hash', sa.String(), nullable=True),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('candidate_action', sa.String(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('gate_status', sa.String(), nullable=False),
        sa.Column('before_context_json', sa.JSON(), nullable=False),
        sa.Column('after_context_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists('decision_snapshots', 'ix_decision_snapshots_created_at'):
        op.create_index(op.f('ix_decision_snapshots_created_at'), 'decision_snapshots', ['created_at'], unique=False)
    if not _index_exists('decision_snapshots', 'ix_decision_snapshots_observed_at'):
        op.create_index(op.f('ix_decision_snapshots_observed_at'), 'decision_snapshots', ['observed_at'], unique=False)
    if not _index_exists('decision_snapshots', 'ix_decision_snapshots_snapshot_id'):
        op.create_index(op.f('ix_decision_snapshots_snapshot_id'), 'decision_snapshots', ['snapshot_id'], unique=True)
    if not _index_exists('decision_snapshots', 'ix_decision_snapshots_symbol'):
        op.create_index(op.f('ix_decision_snapshots_symbol'), 'decision_snapshots', ['symbol'], unique=False)
    if not _index_exists('decision_snapshots', 'ix_decision_snapshots_symbol_timeframe_observed_at'):
        op.create_index('ix_decision_snapshots_symbol_timeframe_observed_at', 'decision_snapshots', ['symbol', 'timeframe', 'observed_at'], unique=False)
    if not _table_exists('drawdowns'):
        op.create_table('drawdowns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('peak_balance', sa.Float(), nullable=False),
        sa.Column('trough_balance', sa.Float(), nullable=False),
        sa.Column('max_drawdown_percentage', sa.Float(), nullable=False),
        sa.Column('drawdown', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists('exchange_configs'):
        op.create_table('exchange_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('api_key_encrypted', sa.Text(), nullable=True),
        sa.Column('secret_key_encrypted', sa.Text(), nullable=True),
        sa.Column('passphrase_encrypted', sa.Text(), nullable=True),
        sa.Column('account_name', sa.String(length=128), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('testnet', sa.Boolean(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists('execution_history'):
        op.create_table('execution_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('execution_id', sa.String(), nullable=False),
        sa.Column('order_id', sa.String(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('market_type', sa.Enum('CRYPTO', 'FOREX', 'INDICES', 'STOCKS', name='markettype'), nullable=False),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('filled_price', sa.Float(), nullable=False),
        sa.Column('filled_quantity', sa.Float(), nullable=False),
        sa.Column('commission', sa.Float(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('execution_id')
        )
    if not _index_exists('execution_history', 'ix_execution_history_symbol_timestamp'):
        op.create_index('ix_execution_history_symbol_timestamp', 'execution_history', ['symbol', 'timestamp'], unique=False)
    if not _table_exists('kill_switch_events'):
        op.create_table('kill_switch_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('reason', sa.String(), nullable=False),
        sa.Column('actor', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists('kill_switch_events', 'ix_kill_switch_events_account_id'):
        op.create_index(op.f('ix_kill_switch_events_account_id'), 'kill_switch_events', ['account_id'], unique=False)
    if not _index_exists('kill_switch_events', 'ix_kill_switch_events_created_at'):
        op.create_index(op.f('ix_kill_switch_events_created_at'), 'kill_switch_events', ['created_at'], unique=False)
    if not _table_exists('market_candles'):
        op.create_table('market_candles',
        sa.Column('symbol', sa.String(length=64), nullable=False),
        sa.Column('timeframe', sa.String(length=16), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('open', sa.Float(), nullable=False),
        sa.Column('high', sa.Float(), nullable=False),
        sa.Column('low', sa.Float(), nullable=False),
        sa.Column('close', sa.Float(), nullable=False),
        sa.Column('volume', sa.Float(), nullable=False),
        sa.Column('source', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('symbol', 'timeframe', 'timestamp')
        )
    if not _index_exists('market_candles', 'ix_market_candles_symbol_timeframe_timestamp'):
        op.create_index('ix_market_candles_symbol_timeframe_timestamp', 'market_candles', ['symbol', 'timeframe', 'timestamp'], unique=False)
    if not _table_exists('market_patterns'):
        op.create_table('market_patterns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('strategy', sa.String(), nullable=False),
        sa.Column('observed_at', sa.DateTime(), nullable=True),
        sa.Column('pattern_type', sa.String(), nullable=False),
        sa.Column('signature_json', sa.JSON(), nullable=False),
        sa.Column('entry_price', sa.Float(), nullable=True),
        sa.Column('atr', sa.Float(), nullable=True),
        sa.Column('outcome_atr', sa.Float(), nullable=True),
        sa.Column('outcome_label', sa.Integer(), nullable=True),
        sa.Column('sample_size', sa.Integer(), nullable=True),
        sa.Column('source_observation_id', sa.Integer(), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists('market_patterns', 'ix_market_patterns_observed_at'):
        op.create_index(op.f('ix_market_patterns_observed_at'), 'market_patterns', ['observed_at'], unique=False)
    if not _index_exists('market_patterns', 'ix_market_patterns_symbol'):
        op.create_index(op.f('ix_market_patterns_symbol'), 'market_patterns', ['symbol'], unique=False)
    if not _table_exists('model_registry'):
        op.create_table('model_registry',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('model_name', sa.String(length=128), nullable=False),
        sa.Column('version', sa.String(length=128), nullable=False),
        sa.Column('artifact_sha256', sa.String(length=64), nullable=False),
        sa.Column('dataset_sha256', sa.String(length=64), nullable=True),
        sa.Column('metrics_oos_json', sa.JSON(), nullable=False),
        sa.Column('training_config_json', sa.JSON(), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('registered_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('version')
        )
    if not _index_exists('model_registry', 'ix_model_registry_name_status'):
        op.create_index('ix_model_registry_name_status', 'model_registry', ['model_name', 'status'], unique=False)
    if not _index_exists('model_registry', 'ix_model_registry_registered_at'):
        op.create_index(op.f('ix_model_registry_registered_at'), 'model_registry', ['registered_at'], unique=False)
    if not _table_exists('monthly_pnl'):
        op.create_table('monthly_pnl',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('month_start_date', sa.DateTime(), nullable=False),
        sa.Column('pnl', sa.Float(), nullable=True),
        sa.Column('drawdown', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists('news_articles'):
        op.create_table('news_articles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('external_id', sa.String(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('summary', sa.String(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('published_at', sa.DateTime(), nullable=True),
        sa.Column('sentiment_score', sa.Float(), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('external_id')
        )
    if not _table_exists('order_history'):
        op.create_table('order_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('order_id', sa.String(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('market_type', sa.Enum('CRYPTO', 'FOREX', 'INDICES', 'STOCKS', name='markettype'), nullable=False),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('order_type', sa.String(), nullable=False),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('quantity', sa.Float(), nullable=True),
        sa.Column('status', sa.Enum('PENDING', 'FILLED', 'PARTIALLY_FILLED', 'CANCELED', 'REJECTED', name='orderstatus'), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('order_id')
        )
    if not _index_exists('order_history', 'ix_order_history_symbol_timestamp'):
        op.create_index('ix_order_history_symbol_timestamp', 'order_history', ['symbol', 'timestamp'], unique=False)
    if not _table_exists('order_intents'):
        op.create_table('order_intents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('client_order_id', sa.String(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('order_type', sa.String(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('exchange_order_id', sa.String(), nullable=True),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column('last_error', sa.String(), nullable=True),
        sa.Column('payload_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists('order_intents', 'ix_order_intents_account_id'):
        op.create_index(op.f('ix_order_intents_account_id'), 'order_intents', ['account_id'], unique=False)
    if not _index_exists('order_intents', 'ix_order_intents_client_order_id'):
        op.create_index(op.f('ix_order_intents_client_order_id'), 'order_intents', ['client_order_id'], unique=True)
    if not _table_exists('positions'):
        op.create_table('positions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('market_type', sa.Enum('CRYPTO', 'FOREX', 'INDICES', 'STOCKS', name='markettype'), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('entry_price', sa.Float(), nullable=False),
        sa.Column('current_price', sa.Float(), nullable=False),
        sa.Column('unrealized_pnl', sa.Float(), nullable=True),
        sa.Column('realized_pnl', sa.Float(), nullable=True),
        sa.Column('is_open', sa.Boolean(), nullable=True),
        sa.Column('open_time', sa.DateTime(), nullable=True),
        sa.Column('close_time', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists('protection_orders'):
        op.create_table('protection_orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('parent_client_order_id', sa.String(), nullable=False),
        sa.Column('client_order_id', sa.String(), nullable=False),
        sa.Column('exchange_order_id', sa.String(), nullable=True),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('order_type', sa.String(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('stop_price', sa.Float(), nullable=True),
        sa.Column('limit_price', sa.Float(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('client_order_id')
        )
    if not _index_exists('protection_orders', 'ix_protection_orders_account_id'):
        op.create_index(op.f('ix_protection_orders_account_id'), 'protection_orders', ['account_id'], unique=False)
    if not _index_exists('protection_orders', 'ix_protection_orders_parent_client_order_id'):
        op.create_index(op.f('ix_protection_orders_parent_client_order_id'), 'protection_orders', ['parent_client_order_id'], unique=False)
    if not _table_exists('reconciliation_snapshots'):
        op.create_table('reconciliation_snapshots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('open_orders_count', sa.Integer(), nullable=True),
        sa.Column('positions_count', sa.Integer(), nullable=True),
        sa.Column('payload_json', sa.JSON(), nullable=True),
        sa.Column('observed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists('reconciliation_snapshots', 'ix_reconciliation_snapshots_account_id'):
        op.create_index(op.f('ix_reconciliation_snapshots_account_id'), 'reconciliation_snapshots', ['account_id'], unique=False)
    if not _index_exists('reconciliation_snapshots', 'ix_reconciliation_snapshots_observed_at'):
        op.create_index(op.f('ix_reconciliation_snapshots_observed_at'), 'reconciliation_snapshots', ['observed_at'], unique=False)
    if not _table_exists('runtime_position_state'):
        op.create_table('runtime_position_state',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('entry_price', sa.Float(), nullable=False),
        sa.Column('stop_loss', sa.Float(), nullable=True),
        sa.Column('take_profit', sa.Float(), nullable=True),
        sa.Column('breakeven_trigger', sa.Float(), nullable=True),
        sa.Column('order_id', sa.String(), nullable=True),
        sa.Column('is_open', sa.Boolean(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists('strategy_configs'):
        op.create_table('strategy_configs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('weight', sa.Float(), nullable=True),
        sa.Column('timeframes', sa.String(length=128), nullable=True),
        sa.Column('stop_loss', sa.Float(), nullable=True),
        sa.Column('take_profit', sa.Float(), nullable=True),
        sa.Column('trailing', sa.Boolean(), nullable=True),
        sa.Column('params_json', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
    if not _table_exists('system_logs'):
        op.create_table('system_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('level', sa.String(), nullable=True),
        sa.Column('account_id', sa.String(), nullable=True),
        sa.Column('message', sa.String(), nullable=True),
        sa.Column('module', sa.String(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists('trades'):
        op.create_table('trades',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('market_type', sa.Enum('CRYPTO', 'FOREX', 'INDICES', 'STOCKS', name='markettype'), nullable=False),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists('trades', 'ix_trades_symbol_timestamp'):
        op.create_index('ix_trades_symbol_timestamp', 'trades', ['symbol', 'timestamp'], unique=False)
    if not _table_exists('trend_snapshots'):
        op.create_table('trend_snapshots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('trend_score', sa.Float(), nullable=True),
        sa.Column('market_cap_rank', sa.Integer(), nullable=True),
        sa.Column('price_change_24h', sa.Float(), nullable=True),
        sa.Column('observed_at', sa.DateTime(), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists('weekly_pnl'):
        op.create_table('weekly_pnl',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.String(), nullable=False),
        sa.Column('week_start_date', sa.DateTime(), nullable=False),
        sa.Column('pnl', sa.Float(), nullable=True),
        sa.Column('drawdown', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists('whale_activity'):
        op.create_table('whale_activity',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('volume', sa.Float(), nullable=False),
        sa.Column('sentiment', sa.String(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists('model_metrics'):
        op.create_table('model_metrics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('model_version', sa.String(length=128), nullable=False),
        sa.Column('metric_name', sa.String(length=64), nullable=False),
        sa.Column('regime', sa.String(length=64), nullable=False),
        sa.Column('split', sa.String(length=32), nullable=False),
        sa.Column('metric_value', sa.Float(), nullable=False),
        sa.Column('measured_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['model_version'], ['model_registry.version'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
        )
    if not _index_exists('model_metrics', 'ix_model_metrics_version_regime_time'):
        op.create_index('ix_model_metrics_version_regime_time', 'model_metrics', ['model_version', 'regime', 'measured_at'], unique=False)
    if op.get_bind().dialect.name == "postgresql" and os.getenv("ENABLE_TIMESCALEDB_HYPERTABLES", "false").lower() in {"1", "true", "yes"}:
        op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
        op.execute("SELECT create_hypertable('market_candles', 'timestamp', if_not_exists => TRUE)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_metrics_version_regime_time', table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_table('whale_activity')
    op.drop_table('weekly_pnl')
    op.drop_table('trend_snapshots')
    op.drop_index('ix_trades_symbol_timestamp', table_name='trades')
    op.drop_table('trades')
    op.drop_table('system_logs')
    op.drop_table('strategy_configs')
    op.drop_table('runtime_position_state')
    op.drop_index(op.f('ix_reconciliation_snapshots_observed_at'), table_name='reconciliation_snapshots')
    op.drop_index(op.f('ix_reconciliation_snapshots_account_id'), table_name='reconciliation_snapshots')
    op.drop_table('reconciliation_snapshots')
    op.drop_index(op.f('ix_protection_orders_parent_client_order_id'), table_name='protection_orders')
    op.drop_index(op.f('ix_protection_orders_account_id'), table_name='protection_orders')
    op.drop_table('protection_orders')
    op.drop_table('positions')
    op.drop_index(op.f('ix_order_intents_client_order_id'), table_name='order_intents')
    op.drop_index(op.f('ix_order_intents_account_id'), table_name='order_intents')
    op.drop_table('order_intents')
    op.drop_index('ix_order_history_symbol_timestamp', table_name='order_history')
    op.drop_table('order_history')
    op.drop_table('news_articles')
    op.drop_table('monthly_pnl')
    op.drop_index(op.f('ix_model_registry_registered_at'), table_name='model_registry')
    op.drop_index('ix_model_registry_name_status', table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_market_patterns_symbol'), table_name='market_patterns')
    op.drop_index(op.f('ix_market_patterns_observed_at'), table_name='market_patterns')
    op.drop_table('market_patterns')
    op.drop_index('ix_market_candles_symbol_timeframe_timestamp', table_name='market_candles')
    op.drop_table('market_candles')
    op.drop_index(op.f('ix_kill_switch_events_created_at'), table_name='kill_switch_events')
    op.drop_index(op.f('ix_kill_switch_events_account_id'), table_name='kill_switch_events')
    op.drop_table('kill_switch_events')
    op.drop_index('ix_execution_history_symbol_timestamp', table_name='execution_history')
    op.drop_table('execution_history')
    op.drop_table('exchange_configs')
    op.drop_table('drawdowns')
    op.drop_index('ix_decision_snapshots_symbol_timeframe_observed_at', table_name='decision_snapshots')
    op.drop_index(op.f('ix_decision_snapshots_symbol'), table_name='decision_snapshots')
    op.drop_index(op.f('ix_decision_snapshots_snapshot_id'), table_name='decision_snapshots')
    op.drop_index(op.f('ix_decision_snapshots_observed_at'), table_name='decision_snapshots')
    op.drop_index(op.f('ix_decision_snapshots_created_at'), table_name='decision_snapshots')
    op.drop_table('decision_snapshots')
    op.drop_index('ix_data_gaps_symbol_timeframe_detected_at', table_name='data_gaps')
    op.drop_table('data_gaps')
    op.drop_table('daily_pnl')
    op.drop_index(op.f('ix_backtest_runs_symbol'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_run_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_created_at'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index('ix_audit_log_actor_created_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('algorithm_configs')
    op.drop_index('ix_ai_observations_symbol_observed_at', table_name='ai_observations')
    op.drop_index(op.f('ix_ai_observations_symbol'), table_name='ai_observations')
    op.drop_index(op.f('ix_ai_observations_observed_at'), table_name='ai_observations')
    op.drop_table('ai_observations')
    op.drop_table('admin_users')
    op.drop_table('account_state')
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS orderstatus")
        op.execute("DROP TYPE IF EXISTS markettype")
    # ### end Alembic commands ###
